# Exercício 009: Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

print('\033[32m*\033[m' * 8)
print('\033[32mTABUADA\033[m')
print('\033[32m*\033[m' * 8)
print('\033[34mDigite um número para descobrir sua tabuada: ')
valor = int(input())
print(f'{valor} X 0 = {valor * 0}')
print(f'{valor} X 1 = {valor * 1}')
print(f'{valor} X 2 = {valor * 2}')
print(f'{valor} X 3 = {valor * 3}')
print(f'{valor} X 4 = {valor * 4}')
print(f'{valor} X 5 = {valor * 5}')
print(f'{valor} X 6 = {valor * 6}')
print(f'{valor} X 7 = {valor * 7}')
print(f'{valor} X 8 = {valor * 8}')
print(f'{valor} X 9 = {valor * 9}')
print(f'{valor} X 10 = {valor * 10}')
